### ISSUE TITLE
Question about the table

### ISSUE THREAD

**Issue by Cassiatora** [khanrc/swad#15]
![image](https://user-images.githubusercontent.com/58909848/184600757-6bcc2c06-c30c-40d4-8fc0-d76c37b2b4d6.png)
Hi, I want to know if every column indicates leave-one-out cross-validations for the target domain accuracy. And oracle uses the small split of the test domain as the validation set (test-domain validation). Is this contradictory to leave-one-out?

**Comment by Cassiatora** [comment]
And if the oracle uses the small split of the test domain as the validation set (test-domain validation), I don't understand why the result of SWAD is better than the result of the oracle? Could you help me to solve the confusion?

**Comment by khanrc** [comment]
You're right. The "oracle" is a kind of cheat setting. In DomainBed, the authors use it to see upper bound on performance by model selection method.

In this table, "oracle" indicates the oracle model selection performance of "ERM". Since SWAD produces only one model, SWAD does not require a model selection method (or, SWAD itself can be viewed as a model selection method).
