### ISSUE TITLE
Can't reproduce the result of ERM.

### ISSUE THREAD

**Issue by justopit** [khanrc/swad#9]
train PACS and Office Home one time, and the result is

Office Home: Last: 62.4, SWAD: 70.8 , Oracle: 66.3
PACS: Last: 82.2, SWAD: 88.3, Oracle: 88.1

The Last result if ERM? It is not consistent with the result of your paper. So the ERM result is Oracle?

**Comment by khanrc** [comment]
The `Last` is not the SWAD results, but the performance of the last model. As you wrote, SWAD results are `70.8` and `88.3`. They are consistent with the results of the paper.

**Comment by justopit** [comment]
So, where I can see the result of ERM w/o SWAD

**Comment by khanrc** [comment]
Our ERM results were from HP search. Searched ERM HPs are different from the SWAD reproduced commands we provided. This repository does not aim to reproduce ERM results, but here are some tips for this: 1) Set HP by referring to https://github.com/khanrc/swad/issues/3#issuecomment-998474029 2) Turn off SWAD 3) Check the `iid` row results instead of `last` or `oracle` row.

**Comment by justopit** [comment]
OK, thank you.
